# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: log_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'log_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11log_service.proto\x12\nlogservice\"\xd7\x02\n\nLogRequest\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x10\n\x08hostname\x18\x02 \x01(\t\x12\x13\n\x0blogger_name\x18\x03 \x01(\t\x12\x0e\n\x06module\x18\x04 \x01(\t\x12 \n\x05level\x18\x05 \x01(\x0e\x32\x11.logservice.Level\x12\x10\n\x08\x66ilename\x18\x06 \x01(\t\x12\x15\n\rfunction_name\x18\x07 \x01(\t\x12\x13\n\x0bline_number\x18\x08 \x01(\t\x12\x0f\n\x07message\x18\t \x01(\t\x12\x11\n\tpath_name\x18\n \x01(\t\x12\x12\n\nprocess_id\x18\x0b \x01(\t\x12\x14\n\x0cprocess_name\x18\x0c \x01(\t\x12\x11\n\tthread_id\x18\r \x01(\t\x12\x13\n\x0bthread_name\x18\x0e \x01(\t\x12\x14\n\x0cservice_name\x18\x0f \x01(\t\x12\x13\n\x0bstack_trace\x18\x10 \x01(\t\"\x1e\n\x0bLogResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08*\x96\x01\n\x05Level\x12\n\n\x06NOTSET\x10\x00\x12\t\n\x05\x44\x45\x42UG\x10\x01\x12\n\n\x06STREAM\x10\x02\x12\x08\n\x04INFO\x10\x03\x12\t\n\x05LOGON\x10\x04\x12\n\n\x06LOGOUT\x10\x05\x12\t\n\x05TRADE\x10\x06\x12\x0c\n\x08SCHEDULE\x10\x07\x12\n\n\x06REPORT\x10\x08\x12\x0b\n\x07WARNING\x10\t\x12\t\n\x05\x45RROR\x10\n\x12\x0c\n\x08\x43RITICAL\x10\x0b\x32K\n\nLogService\x12=\n\nLogMessage\x12\x16.logservice.LogRequest\x1a\x17.logservice.LogResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'log_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LEVEL']._serialized_start=412
  _globals['_LEVEL']._serialized_end=562
  _globals['_LOGREQUEST']._serialized_start=34
  _globals['_LOGREQUEST']._serialized_end=377
  _globals['_LOGRESPONSE']._serialized_start=379
  _globals['_LOGRESPONSE']._serialized_end=409
  _globals['_LOGSERVICE']._serialized_start=564
  _globals['_LOGSERVICE']._serialized_end=639
# @@protoc_insertion_point(module_scope)
